apiVersion: v2
name: owasp-modsecurity
description: owasp/modsecurity-crs Helm chart for Kubernetes
keywords:
  - cluster
  - security
  - WAF
home: https://hub.docker.com/r/owasp/modsecurity-crs/tags
type: application
version: 0.1.1
appVersion: "3.3.2"
